language: android
sudo: required
jdk:
  - oraclejdk8 # lambda support
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-26
    #- sys-img-armeabi-v7a-android-17
    
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - chmod +x gradlew
  - ./gradlew dependencies || true # DON'T ADD unless you are getting "Install missing components using SDK manager"
  #Source: https://medium.com/@oldergod/constraint-layout-and-circleci-travis-d50342696d2
    
script:
  - sdkmanager --update && yes | sdkmanager --licenses
  - ./gradlew build test
